tools:
    external_code_coverage: false
        #timeout: 900
    sensiolabs_security_checker: true
    php_code_coverage:
        enabled: true
    php_analyzer:
        config:
            verify_php_doc_comments:
                suggest_more_specific_types: false

checks:
    php:
        code_rating: true
