#!/usr/bin/env php
<?php

/**
 * This file is part of the ApiGen (http://apigen.org)
 *
 * For the full copyright and license information, please view
 * the file license.md that was distributed with this source code.
 */

namespace ApiGen;

use Nette\Configurator;
use TokenReflection;
use Tracy\Debugger;


require_once 'vendor/autoload.php';

// Safe locale and timezone
setlocale(LC_ALL, 'C');
if ( ! ini_get('date.timezone')) {
	date_default_timezone_set('UTC');
}

// ApiGen root path
define('APIGEN_ROOT_PATH', __DIR__ . '/src');

// Init debugger
Debugger::$strictMode = TRUE;
Debugger::enable(Debugger::DEVELOPMENT, FALSE);

// Build the DIC
$configurator = new Configurator;
$configurator->setTempDirectory(__DIR__ . '/temp');
$configurator->addConfig(__DIR__ . '/src/ApiGen/DI/config.neon');
$container = $configurator->createContainer();

// Update debugger configuration if needed
if ( ! $container->getService('apigen.configuration')->debug) {
	Debugger::enable(Debugger::PRODUCTION, TRUE);
	Debugger::$onFatalError[] = function() {
		echo "\nFor more information turn on the debug mode using the --debug option.\n";
	};
}

// Let's rock
$container->getByType('ApiGen\Application\Application')->run();
