<table class="summary" id="classes">
<caption>Class summary</caption>
{foreach $classes as $class}
{continueIf $class->interface}
<tr>
	<td width="20%"><a href="{$class|classLink}">{ifset $namespace}{$class->shortName}{else}{$class->name}{/if}</a></td>
	<td>{!$class->docComment|docline}</td>
</tr>
{/foreach}
</table>

<table class="summary" id="interfaces">
<caption>Interface summary</caption>
{foreach $classes as $class}
{continueIf !$class->interface}
<tr>
	<td width="20%"><a href="{$class|classLink}">{ifset $namespace}{$class->shortName}{else}{$class->name}{/if}</a></td>
	<td>{!$class->docComment|docline}</td>
</tr>
{/foreach}
</table>