{if $classes}
<table class="summary" id="classes">
<caption>Class summary</caption>
{foreach $classes as $class}
<tr>
	<td width="20%"><a href="{$class|classLink}">{ifset $namespace}{$class->shortName}{else}{$class->name}{/if}</a></td>
	<td>{!$class->docComment|docline}</td>
</tr>
{/foreach}
</table>
{/if}

{if $interfaces}
<table class="summary" id="interfaces">
<caption>Interface summary</caption>
{foreach $interfaces as $interface}
<tr>
	<td width="20%"><a href="{$interface|classLink}">{ifset $namespace}{$interface->shortName}{else}{$interface->name}{/if}</a></td>
	<td>{!$interface->docComment|docline}</td>
</tr>
{/foreach}
</table>
{/if}