{layout @layout.phtml}

{block #title}Namespace {$namespace}{/block}

{block #content}
<div id="navigation">
	<ul>
		<li><a href="overview.html" title="Summary of all namespaces">Overview</a></li>
		<li {ifset $namespace}class="active"{/if}>Namespace</li>
		<li>Class</li>
		<li><a href="elements.html">Elements</a></li>
	</ul>
</div>

<div id="content">
	<h1>{ifset $namespace}{if $namespace}Namespace {$namespace}{else}No namespace{/if}{else}All Classes{/if}</h1>

	<table class="summary">
	<caption>Class summary</caption>
	{foreach $classes as $class}
	{continueIf $class->interface}
	<tr>
		<td width="20%"><a href="{$class|classLink}">{$class->shortName}</a></td>
		<td>{!$class->docComment|docline}</td>
	</tr>
	{/foreach}
	</table>

	<table class="summary">
	<caption>Interface summary</caption>
	{foreach $classes as $class}
	{continueIf !$class->interface}
	<tr>
		<td width="20%"><a href="{$class|classLink}">{$class->shortName}</a></td>
		<td>{!$class->docComment|docline}</td>
	</tr>
	{/foreach}
	</table>
</div>
{/block}