{layout @layout.phtml}
{var $noindex => TRUE}

{block #title}File {$fileName}{/block}

{block #content}
<div id="navigation">
	<ul>
		<li><a href="overview.html" title="Summary of all namespaces">Overview</a></li>
		<li>{if $namespace}<a href="{$class|namespaceLink}" title="Summary of {$class->namespaceName}">Namespace</a>{else}Namespace{/if}</li>
		<li>{if $package}<a href="{$package|packageLink}" title="Summary of {$package}">Package</a>{else}Package{/if}</li>
		<li><a href="{$class|classLink}" title="Summary of {$class}">Class</a></li>
	</ul>
</div>

<pre><code>{!$source|replaceRE:'#<span class="count">(\s*(\d+):\s*)</span>#','<a href="#$2" id="$2" class="l">$1</a>'}</code></pre>
{/block}