{layout @layout.phtml}

{block #content}
<div id="navigation">
	<ul>
		<li class="active">Overview</li>
		<li>Namespace</li>
		<li>Class</li>
		<li><a href="elements.html">Elements</a></li>
	</ul>
</div>

<div id="content">
	<h1>{$title} Overview</h1>

	<table class="summary">
	<caption>Packages</caption>
	{foreach $packages as $package}
	<tr>
		<td><a href="{$package|packageLink}">{$package ? $package : 'none'}</a></td>
	</tr>
	{/foreach}
	</table>

	<table class="summary">
	<caption>Namespaces</caption>
	{foreach $namespaces as $namespace}
	<tr>
		<td><a href="{$namespace|namespaceLink}">{$namespace ? $namespace : 'none'}</a></td>
	</tr>
	{/foreach}
	</table>
</div>
{/block}