name: GitHub Pages

on:
  push:
    branches: ['master']

jobs:
  pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --no-dev

      - name: Build Pages
        run: bin/apigen --title ApiGen src

      - name: Publish Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: api
          branch: gh-pages
